server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 172.23.151.125
      port: 6379
      password: 123321
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: b512c9ad70874e70fe37f81252501abe
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com